services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: gtfs
      POSTGRES_PASSWORD: gtfs
      POSTGRES_DB: gtfs_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: